const WEATHER_INTERPRETATION = [
    {
        codes: 0,
        image:"sunny",
        back_image:require("../assets/images/sunny_large.png"),
        label: "Ciel dégagé",
        color: ["#FFE79A", "#FFFFFF"]
    },
    {
        codes: 1,
        image:"sunny",
        back_image:require("../assets/images/sunny_large.png"),
        label: "Ciel clair",
        color: ["#FFE79A", "#FFFFFF"]
    },
    {
        codes: 2,
        image:"partly-sunny",
        back_image:require("../assets/images/sunny_large.png"),
        label: "Partiellement nuageux",
        color: ["#FFE79A", "#FFFFFF"],
    },
    {
        codes: 3,
        image: "cloudy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Couvert",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 45,
        image:"cloudy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Brouillard",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 48,
        image:"cloudy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Brouillard de chaux",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 51,
        image:"rainy-outline",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Bruine légère",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 53,
        image:"rainy-outline",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Bruine modérée",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 55,
        image:"rainy-outline",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Bruine dense",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 56,
        image:"cloudy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Brouillard givrant léger",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 57,
        image:"cloudy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Brouillard givrant dense",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 61,
        image:"rainy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Pluie légére",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 63,
        image:"rainy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Pluie modérée",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 65,
        image:"rainy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Pluie intense",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 66,
        image:"rainy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Pluie verglaçante légére",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 67,
        image:"rainy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Pluie verglaçante intense",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 71,
        image:"snow-outline",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Chute de neige légére",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 73,
        image:"snow-outline",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Chute de neige modérée",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 75,
        image:"snow-outline",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Chute de neige intense",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 77,
        image:"snow",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Grêle",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 80,
        image:"rainy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Averses légére",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 81,
        image:"rainy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Averses modérée",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 82,
        image:"rainy",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Averses violente",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 85,
        image:"snow",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Averse de neige légére",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 86,
        image:"snow",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Averses de neige abondantes",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 95,
        image:"thunderstorm-outline",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Légèrement orageux",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 96,
        image:"thunderstorm",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Orage avec grêle légère",
        color: ["#C0DFFE", "#FFFFFF"],
    },
    {
        codes: 99,
        image:"thunderstorm",
        back_image:require("../assets/images/cloudy_large.png"),
        label: "Orage avec grêle forte",
        color: ["#C0DFFE", "#FFFFFF"],
    },
];

export function getWeatherInterpretation(code) {
    return WEATHER_INTERPRETATION.find((interpretation) => interpretation.codes === code)
}